services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/aidevworkflow
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aidevworkflow

  code-planner-agent:
    build:
      context: ./agents/code-planner
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

  code-generator-agent:
    build:
      context: ./agents/code-generator
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

  code-reviewer-agent:
    build:
      context: ./agents/code-reviewer
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge
